apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lucian-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /lucian(.*)
        pathType: Prefix
        backend:
          service:
            name: lucian-simple-web
            port:
              number: 80
  ingressClassName: nginx